// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://auvihrvwfjzqchnvvwcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1dmlocnZ3Zmp6cWNobnZ2d2NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDg0NTksImV4cCI6MjA3MDEyNDQ1OX0.6SOsb7LZB8holNUO8j_FgAPT21MFL2g5YL8zFo3Zuvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});